const identity=require('../../utils/identity'),service=require('../../utils/workspace'),store=require('../../utils/store'),copy=require('../../utils/workspaceCopy');
Page({
 data:{labels:copy(),locked:true,busy:false,message:'',tasks:[],jobs:[],task:null,preview:[],remote:null,partnerProfile:null,config:{},pending:false,taskCursor:'',jobCursor:'',reminderTitle:'',date:'',time:'12:00',feedbackMessage:'',contact:'',avatarSelected:false,profileRead:false,dusk:false},
 onLoad(){this._hidden=false;this.off=identity.subscribe(()=>this.reset());this.reset();},
 onShow(){this._hidden=false;this.reset();},
 onHide(){this._hidden=true;this.clearPrivate();},
 onUnload(){this._disposed=true;if(this.off)this.off();this.clearPrivate();},
 clearPrivate(){if(this._partnerTimer)clearTimeout(this._partnerTimer);this._partnerTimer=null;this._remote=null;this._avatar=null;this.setData({tasks:[],jobs:[],task:null,preview:[],remote:null,partnerProfile:null,message:'',feedbackMessage:'',contact:'',reminderTitle:'',avatarSelected:false,profileRead:false,busy:false});},
 reset(){this.clearPrivate();const s=identity.snapshot();const draft=!s.locked&&identity.workspaceDraft()||{};this.setData({labels:copy(),locked:s.locked,pending:!s.locked&&!!identity.workspaceIntent(),config:{},date:require('../../utils/localDate').shift(require('../../utils/localDate').today(),1),dusk:store.get().settings.theme==='dusk',...draft});wx.setNavigationBarTitle({title:copy().title});if(!s.locked&&!this._hidden)this.refresh();},
 alive(token){return !this._disposed&&!this._hidden&&identity.isCurrent(token);},
 async run(fn){if(this.data.busy||this.data.locked)return;const token=identity.lease();this.setData({busy:true,message:''});try{await fn(token);if(this.alive(token))this.setData({pending:!!identity.workspaceIntent()});}catch(e){if(this.alive(token))this.setData({message:e.code||e.message||'WORKSPACE_UNAVAILABLE',pending:!!identity.workspaceIntent()});}finally{if(this.alive(token))this.setData({busy:false});}},
 async confirm(content,token){const r=await new Promise((resolve,reject)=>wx.showModal({title:copy().confirm,content,success:resolve,fail:reject}));identity.assertLease(token);return r.confirm&&this.alive(token);},
 refresh(){return this.run(async token=>{const results=await Promise.all([service.call('config',{},token),service.call('listTasks',{},token),service.call('listJobs',{},token)]);if(this.alive(token))this.setData({config:results[0],tasks:results[1].items,taskCursor:results[1].cursor,jobs:results[2].items,jobCursor:results[2].cursor,message:copy().ready});});},
 nextTasks(){return this.run(async token=>{const r=await service.call('listTasks',{cursor:this.data.taskCursor},token);if(this.alive(token))this.setData({tasks:r.items,taskCursor:r.cursor});});},
 nextJobs(){return this.run(async token=>{const r=await service.call('listJobs',{cursor:this.data.jobCursor},token);if(this.alive(token))this.setData({jobs:r.items,jobCursor:r.cursor});});},
 readCloud(){return this.run(async token=>{await store.refreshCloudReadOnly();if(this.alive(token))this.setData({message:copy().done});});},
 backup(){return this.run(async token=>{if(!await this.confirm(copy().backupHint,token))return;const r=await service.createArchive(service.localRows(),'backup');if(this.alive(token))this.setData({task:r.task,message:copy().done});});},
 importFile(){return this.run(async token=>{
  const result=await new Promise((resolve,reject)=>wx.chooseMessageFile({count:1,type:'file',extension:['json'],success:resolve,fail:reject}));token=await identity.resumeNative(token);if(!this.alive(token))return;
  const f=result.tempFiles[0];if(!f||f.size>5*1024*1024)throw new Error('ARCHIVE_TOO_LARGE');
  const raw=wx.getFileSystemManager().readFileSync(f.path,'utf8'),rows=service.parseArchive(raw);
  if(!await this.confirm(copy().backupHint+'\n'+rows.length+' records',token))return;
  const r=await service.createArchive(rows,'import',raw);if(this.alive(token))this.setData({task:r.task,preview:rows.slice(0,5).map((x,i)=>({key:String(i),restaurantName:x.restaurantName,date:x.date})),message:copy().done});
 });},
 retry(){return this.run(async token=>{const r=await service.retry();if(this.alive(token))this.setData({task:r.task||null,message:r.job?r.job.state:copy().done});});},
 preserve(){return this.run(async token=>{if(!await this.confirm(copy().preserveConsent,token))return;const path=service.preservePending();if(this.alive(token))this.setData({message:path});});},
 selectTask(event){return this.run(async token=>{const r=await service.call('taskStatus',{taskId:event.currentTarget.dataset.id},token);let rows=[];if(r.task.uploaded)rows=(await service.call('getChunk',{taskId:r.task.id,index:0},token)).rows;if(this.alive(token))this.setData({task:r.task,preview:rows.map((x,i)=>({key:String(i),restaurantName:x.restaurantName,date:x.date}))});});},
 restore(){return this.run(async token=>{const task=this.data.task;if(!task||!await this.confirm(copy().backupHint+'\n'+task.count+' records / '+task.photoRefsRemoved+' photo refs removed',token))return;let r=await service.call('commitTask',{taskId:task.id,manifest:task.manifest,consent:true},token);r=await service.finishTask(r.task);if(this.alive(token))this.setData({task:r.task,message:copy().done});await store.refreshCloudReadOnly();});},
 resume(){return this.run(async token=>{const r=await service.finishTask(this.data.task);if(this.alive(token))this.setData({task:r.task,message:copy().done});await store.refreshCloudReadOnly();});},
 cancel(){return this.run(async token=>{if(!await this.confirm(copy().cancel,token))return;const r=await service.call('cancelTask',{taskId:this.data.task.id},token);if(this.alive(token))this.setData({task:r.task});});},
 exportTask(){return this.run(async token=>{if(!await this.confirm(copy().backupHint,token))return;const filePath=await service.exportTask(this.data.task);if(this.alive(token)){this.setData({message:filePath});if(wx.shareFileMessage)wx.shareFileMessage({filePath});}});},
 grant(){return this.profileGrant('grantProfile');},
 revoke(){return this.profileGrant('revokeProfile');},
 profileGrant(action){return this.run(async token=>{if(!this._remote||!await this.confirm(copy().grantHint,token))return;const space=this.data.config.space;const r=await service.mutate(action,{revision:this._remote.revision,spaceId:space&&space.id||'',membershipVersion:space&&space.version||0,consent:true});if(this.alive(token)){this._remote=null;this.setData({profileRead:false,remote:null,message:copy().revision+' '+r.revision});}});},
 partner(){return this.run(async token=>{const space=this.data.config.space;if(!space)return;const r=await service.call('getPartnerProfile',{spaceId:space.id,membershipVersion:space.version},token);if(this.alive(token)){if(this._partnerTimer)clearTimeout(this._partnerTimer);this.setData({partnerProfile:r.profile,message:r.profile?copy().ready:copy().noProfile});this._partnerTimer=setTimeout(()=>{if(this.alive(token))this.setData({partnerProfile:null});},Math.min(15000,r.leaseMs||15000));}});},
 pull(){return this.run(async token=>{const r=await service.call('getProfile',{},token);if(this.alive(token)){this._remote=r.profile;this.setData({profileRead:true,remote:r.profile?{revision:r.profile.revision,name:r.profile.profile.name,bio:r.profile.profile.bio,preferences:JSON.stringify(r.profile.preferences)}:null,message:r.profile?copy().ready:copy().noProfile});}});},
 avatar(){return this.run(async token=>{const base64=await service.chooseAvatar();token=await identity.resumeNative(token);if(this.alive(token)){this._avatar=base64;this.setData({avatarSelected:true,message:copy().selected});}});},
 push(){return this.run(async token=>{if(!this.data.profileRead)return;if(!await this.confirm(copy().profileHint,token))return;const payload=service.profilePayload();payload.profile.avatar=this._avatar||(this._remote&&this._remote.profile.avatar&&this._remote.profile.avatar.base64)||null;const r=await service.mutate('pushProfile',{payload,revision:this._remote?this._remote.revision:0,consent:true});if(this.alive(token)){this._remote=null;this._avatar=null;this.setData({profileRead:false,remote:null,avatarSelected:false,message:copy().revision+' '+r.revision});}});},
 apply(){return this.run(async token=>{if(!this._remote||!await this.confirm(copy().profileConsent,token))return;service.applyProfile(this._remote);if(this.alive(token))this.setData({message:copy().done});});},
 input(e){const key=e.currentTarget.dataset.key;if(['reminderTitle','feedbackMessage','contact','date','time'].includes(key)){try{identity.saveWorkspaceDraft({...identity.workspaceDraft(),[key]:e.detail.value});this.setData({[key]:e.detail.value});}catch(error){this.setData({message:error.code||error.message});}}},
 schedule(){
  // Native permission is invoked directly from the user gesture, never on show.
  if(this.data.busy||this.data.locked)return;const token=identity.lease(),c=this.data.config;if(!c.reminderReady||!wx.requestSubscribeMessage){this.setData({message:copy().notReady});return;}
  if(identity.workspaceIntent()){this.setData({message:copy().pending});return;}
  const date=new Date(this.data.date+'T'+this.data.time+':00'),dueAt=date.getTime(),title=this.data.reminderTitle.trim();if(!title||!Number.isFinite(dueAt)||dueAt<Date.now()+60000){this.setData({message:'INVALID_REMINDER'});return;}
  let resumedToken=token;this.setData({busy:true});wx.requestSubscribeMessage({tmplIds:[c.templateId],success:async r=>{try{const next=await identity.resumeNative(token);resumedToken=next;if(!this.alive(next))return;if(r[c.templateId]!=='accept'){this.setData({message:'SUBSCRIPTION_REQUIRED'});return;}const result=await service.mutate('scheduleReminder',{title,dueAt,timezoneOffset:date.getTimezoneOffset(),templateId:c.templateId,subscriptionAccepted:true,consent:true});if(this.alive(next))this.setData({message:result.job.state,jobs:[result.job].concat(this.data.jobs),pending:false});}catch(e){if(this.alive(resumedToken))this.setData({message:e.code||e.message,pending:!!identity.workspaceIntent()});}finally{if(this.alive(resumedToken))this.setData({busy:false});}},fail:()=>{if(this.alive(token))this.setData({busy:false,message:'SUBSCRIPTION_REQUIRED'});}});
 },
 send(){return this.run(async token=>{const message=this.data.feedbackMessage.trim(),contact=this.data.contact.trim();if(!message||!await this.confirm(copy().sendConsent,token))return;const r=await service.mutate('submitFeedback',{message,contact,consent:true});if(this.alive(token)){this.setData({message:r.job.state,jobs:[r.job].concat(this.data.jobs)});try{identity.saveWorkspaceDraft({...identity.workspaceDraft(),feedbackMessage:'',contact:''});this.setData({feedbackMessage:'',contact:''});}catch(e){this.setData({message:r.job.state+' / LOCAL_DRAFT_NOT_CLEARED'});}}});},
 cancelJob(e){return this.jobAction('cancelJob',e,copy().jobCancel);},
 retryJob(e){return this.jobAction('retryJob',e,copy().jobRetry);},
 jobAction(action,e,content){const jobId=e.currentTarget.dataset.id;return this.run(async token=>{if(!await this.confirm(content,token))return;const r=await service.call(action,{jobId,consent:true},token);if(this.alive(token))this.setData({jobs:this.data.jobs.map(j=>j.id===jobId?r.job:j),message:r.job.state});});},
 reports(){wx.navigateTo({url:'/pages/reports/index'});}
});
