#!/usr/bin/env node
// Offline generation from approved official SVGs, no runtime packages or network.
const fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..'),dir=path.join(root,'miniprogram/images/icons/lucide');
const aliases=require('./icon-aliases.json'),nodes={},icons={};
for(const file of fs.readdirSync(dir).filter(f=>f.endsWith('.svg')).sort()){
 const name=file.slice(0,-4),source=fs.readFileSync(path.join(dir,file),'utf8');nodes[name]=[];
 for(const m of source.matchAll(/<(path|line|rect|circle|ellipse|polyline|polygon)\s+([^>]+)\/>/g)){
  const attrs={};for(const a of m[2].matchAll(/([\w-]+)="([^"]*)"/g))attrs[a[1]]=a[2];nodes[name].push([m[1],attrs]);
 }
 if(!nodes[name].length)throw new Error('Empty SVG: '+name);
 icons[name]=nodes[name].map(([tag,attrs])=>'<'+tag+' '+Object.entries(attrs).map(([k,v])=>k+'="'+v+'"').join(' ')+'/>').join('');
}
const utility=`// Generated by tools/build-icons.cjs from official SVGs; ISC. Do not hand-edit paths.
const icons = ${JSON.stringify(icons,null,2)};
const aliases = ${JSON.stringify(aliases)};
Object.keys(aliases).forEach(name => { icons[name] = icons[aliases[name]]; });
const EXTRA = { fill: 'none', stroke: '#1b1c1a', strokeWidth: 1.75 };
function iconSvg(name, options) {
  const body = icons[name];
  if (!body) return '';
  const opts = Object.assign({}, EXTRA, options || {});
  const svg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="' + opts.fill
    + '" stroke="' + opts.stroke + '" stroke-width="' + opts.strokeWidth
    + '" stroke-linecap="round" stroke-linejoin="round">' + body + '</svg>';
  return 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(svg);
}
module.exports = { icons, iconSvg };
`;
fs.writeFileSync(path.join(root,'miniprogram/utils/icons.js'),utility);
fs.writeFileSync(path.join(root,'miniprogram/utils/lucideMorphNodes.js'),'// Generated from official Lucide SVGs by tools/build-icons.cjs; ISC.\nmodule.exports='+JSON.stringify(nodes)+';\n');
fs.writeFileSync(path.join(__dirname,'_gen/icons.json'),JSON.stringify(icons,null,2)+'\n');
console.log('Generated '+Object.keys(nodes).length+' official shapes + '+Object.keys(aliases).length+' compatibility names (no duplicate geometry source).');
