// Real spaces domain handler; serializable in-memory transaction model.
// CloudBase SDK transaction semantics and real device UI remain final-batch tests.
const assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const {createHandler}=require('../cloudfunctions/spaces/handler');
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
let actor='A',clock=1700000000000,db=new Map(),serial=Promise.resolve(),seq=0;
const uid=name=>'u_'+name.toLowerCase().repeat(48),accountKey=name=>hash(JSON.stringify(['app',name]));
const clone=v=>v===undefined?null:JSON.parse(JSON.stringify(v));
const key=(c,id)=>c+'/'+id;
for(const name of ['A','B','C','D'])db.set(key('savor_accounts',accountKey(name)),{_id:accountKey(name),userId:uid(name),membershipVersion:0});
const handler=createHandler({context:()=>({OPENID:actor,APPID:'app'}),now:()=>clock,repository:{transaction(fn){const result=serial.then(async()=>{const draft=new Map([...db].map(([k,v])=>[k,clone(v)]));const response=await fn({get:async(c,id)=>clone(draft.get(key(c,id))),set:async(c,id,v)=>{draft.set(key(c,id),clone(v));}});db=draft;return response;});serial=result.catch(()=>{});return result;}}});
const call=(name,action,args={})=>{actor=name;return handler({protocolVersion:1,expectedUserId:uid(name),action,operationId:'operation_'+(++seq),...args});};
let count=0;async function test(name,fn){await fn();count++;console.log('PASS '+name);}
let invitation,space,wish,meal;
const scope=()=>({spaceId:space.id,membershipVersion:space.version});
(async()=>{
 await test('forged product identity is rejected without writes',async()=>{const before=JSON.stringify([...db]);const result=await call('A','status',{expectedUserId:uid('B'),OPENID:'B'});assert.equal(result.code,'IDENTITY_MISMATCH');assert.equal(JSON.stringify([...db]),before);});
 await test('invite creation is opaque, expiring and idempotent',async()=>{const request='invite_request_0001';const a=await call('A','createInvite',{operationId:request}),b=await call('A','createInvite',{operationId:request});assert(a.success);assert.equal(a.invitation.token,b.invitation.token);assert.match(a.invitation.token,/^[a-f0-9]{64}$/);assert.equal(a.invitation.expiresAt-clock,86400000);invitation=a.invitation;});
 await test('preview does not bind accounts or disclose the inviter profile',async()=>{const before=JSON.stringify([...db]);const result=await call('B','previewInvite',{token:invitation.token});assert(result.success&&result.preview.requiresConsent);assert(!JSON.stringify(result).includes(uid('A')));assert.equal(JSON.stringify([...db]),before);});
 await test('self accept, missing consent and foreign revocation cannot bind',async()=>{assert.equal((await call('A','acceptInvite',{token:invitation.token,consent:true})).code,'INVITE_UNAVAILABLE');assert.equal((await call('B','acceptInvite',{token:invitation.token})).code,'CONSENT_REQUIRED');assert.equal((await call('B','revokeInvite',{token:invitation.token})).code,'FORBIDDEN');});
 await test('two concurrent acceptors produce exactly one two-member space',async()=>{const results=await Promise.all([call('B','acceptInvite',{token:invitation.token,consent:true}),call('C','acceptInvite',{token:invitation.token,consent:true})]);assert(results[0].success);assert(!results[1].success);space=results[0].space;assert.deepEqual(space.members.map(m=>m.userId),[uid('A'),uid('B')]);assert.equal([...db.keys()].filter(k=>k.startsWith('savor_spaces/')).length,1);});
 await test('accept retry restores result and bound owner cannot make another invite',async()=>{const result=await call('B','acceptInvite',{token:invitation.token,consent:true});assert.equal(result.space.id,space.id);assert.equal((await call('A','createInvite')).code,'ALREADY_BOUND');});
 await test('stale space version and third-party reads fail closed',async()=>{assert.equal((await call('A','list',{...scope(),membershipVersion:99})).code,'MEMBERSHIP_CHANGED');assert.equal((await call('C','list',scope())).code,'SPACE_REQUIRED');});
 await test('joint wishlist create is idempotent and actor preference is server-owned',async()=>{const args={...scope(),title:'Dinner together',note:'Saturday',operationId:'wish_add_repeat_01',preferences:{[uid('B')]:'want'}};const r=await call('A','addWish',args),repeat=await call('A','addWish',args);assert(r.success);assert.equal(r.wish._id,repeat.wish._id);assert.deepEqual(r.wish.preferences,{[uid('A')]:'want'});wish=r.wish;});
 await test('partners can only change their own preference with conflict checking',async()=>{const r=await call('B','wishPreference',{...scope(),id:wish._id,revision:wish.revision,preference:'maybe',userId:uid('A')});assert(r.success);assert.equal(r.wish.preferences[uid('A')],'want');assert.equal(r.wish.preferences[uid('B')],'maybe');assert.equal((await call('A','wishPreference',{...scope(),id:wish._id,revision:1,preference:'no'})).code,'CONFLICT');wish=r.wish;});
 await test('shared wish status can become eaten but only creator may delete',async()=>{const r=await call('B','wishStatus',{...scope(),id:wish._id,revision:wish.revision,status:'eaten'});assert(r.success);wish=r.wish;assert.equal((await call('B','wishStatus',{...scope(),id:wish._id,revision:wish.revision,status:'deleted'})).code,'FORBIDDEN');});
 db.set(key('dining_records','private-meal-a'),{_id:'private-meal-a',createdBy:'A',restaurantName:'Private dinner',note:'Explicit text',date:'2026-09-14',photos:['cloud://private-secret'],ratings:{oldA:5,oldB:2},shared:true,revision:1});
 await test('old shared flag does not auto-publish anything',async()=>{const result=await call('B','list',scope());assert.equal(result.meals.length,0);assert.equal(result.wishes.length,1);});
 await test('publication requires owner and explicit consent',async()=>{assert.equal((await call('B','publishMeal',{...scope(),recordId:'private-meal-a',consent:true})).code,'NOT_FOUND');assert.equal((await call('A','publishMeal',{...scope(),recordId:'private-meal-a'})).code,'CONSENT_REQUIRED');});
 await test('publication copies allowed text but neither old votes nor private photo identifiers',async()=>{const r=await call('A','publishMeal',{...scope(),recordId:'private-meal-a',consent:true});assert(r.success);meal=r.meal;assert.equal(meal.payload.restaurantName,'Private dinner');assert(!JSON.stringify(meal).includes('cloud://'));assert.deepEqual(meal.ratings,{});assert(!meal.payload.createdBy);});
 await test('each account votes independently; supplied foreign votes are ignored',async()=>{const r=await call('A','rateMeal',{...scope(),id:meal._id,revision:meal.revision,rating:4,ratings:{[uid('B')]:5}});assert.deepEqual(r.meal.ratings,{[uid('A')]:4});meal=r.meal;const b=await call('B','rateMeal',{...scope(),id:meal._id,revision:meal.revision,rating:2});assert.deepEqual(b.meal.ratings,{[uid('A')]:4,[uid('B')]:2});meal=b.meal;});
 await test('withdrawing a vote removes only the actual caller and validates score bounds',async()=>{assert.equal((await call('B','rateMeal',{...scope(),id:meal._id,revision:meal.revision,rating:8})).code,'INVALID_RATING');const r=await call('A','rateMeal',{...scope(),id:meal._id,revision:meal.revision,rating:0});assert.deepEqual(r.meal.ratings,{[uid('B')]:2});meal=r.meal;});
 await test('only publisher can retract; retries do not resurrect shared content',async()=>{assert.equal((await call('B','retractMeal',{...scope(),id:meal._id,revision:meal.revision})).code,'FORBIDDEN');const args={...scope(),id:meal._id,revision:meal.revision,operationId:'retract_retry_01'};assert((await call('A','retractMeal',args)).success);const retry=await call('A','retractMeal',args);assert(retry.success&&!retry.meal.active);assert.equal((await call('B','list',scope())).meals.length,0);});
 await test('owner can explicitly republish retracted text with a fresh revision, never by an old request',async()=>{const state=await call('A','publicationState',{...scope(),recordId:'private-meal-a'});assert.equal(state.publication.active,false);const published=await call('A','publishMeal',{...scope(),recordId:'private-meal-a',revision:state.publication.revision,consent:true});assert(published.success&&published.meal.active);assert.equal((await call('B','publicationState',{...scope(),recordId:'private-meal-a'})).code,'NOT_FOUND');});
 await test('either member may leave atomically; both lose shared access but private data survives',async()=>{const args={...scope(),consent:true,operationId:'leave_retry_01'};const r=await call('B','leave',args);assert(r.success);assert((await call('B','leave',args)).success);assert.equal((await call('A','list',scope())).code,'SPACE_REQUIRED');assert.equal((await call('B','list',scope())).code,'SPACE_REQUIRED');assert(db.has(key('dining_records','private-meal-a')));assert(db.has(key('savor_wishes',wish._id)));});
 await test('old accepted invitation cannot create a new space after leaving',async()=>{assert.equal((await call('B','acceptInvite',{token:invitation.token,consent:true})).code,'INVITE_UNAVAILABLE');});
 await test('revoked and expired invitations never bind',async()=>{clock+=61000;const i=await call('A','createInvite');assert(i.success);assert((await call('A','revokeInvite',{token:i.invitation.token})).success);assert.equal((await call('D','acceptInvite',{token:i.invitation.token,consent:true})).code,'INVITE_UNAVAILABLE');clock+=61000;const next=await call('A','createInvite');clock+=86400001;assert.equal((await call('D','acceptInvite',{token:next.invitation.token,consent:true})).code,'INVITE_UNAVAILABLE');});
 await test('new partner space does not inherit previous shared items or votes',async()=>{clock+=61000;const i=await call('A','createInvite');const joined=await call('D','acceptInvite',{token:i.invitation.token,consent:true});assert(joined.success);const newSpace=joined.space;const fresh=await call('D','list',{spaceId:joined.space.id,membershipVersion:joined.space.version});assert.equal(fresh.wishes.length,0);assert.equal(fresh.meals.length,0);assert.equal((await call('A','list',scope())).code,'MEMBERSHIP_CHANGED');space=newSpace;});
 let generation=1,loseReply=false,delayReply=null,slow=false,privateDraft={restaurant:'',photos:[]};const intents=new Map();
 const clientIdentity={lease:()=>({userId:uid(actor),generation}),assertLease(token){if(token.userId!==uid(actor)||token.generation!==generation)throw Object.assign(new Error('STALE_IDENTITY'),{code:'STALE_IDENTITY'});},spaceIntent:()=>clone(intents.get(actor)),saveSpaceIntent(intent){if(intent&&intent.actorUserId!==uid(actor))throw Error('wrong actor');intents.set(actor,clone(intent));}};
 function client(){const module={exports:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../miniprogram/utils/spaces.js'),'utf8'),{module,exports:module.exports,Date:{now:()=>clock},require:name=>name==='./identity'?clientIdentity:name==='./data'?{createId:()=> 'client_op_'+(++seq)}:name==='./cloudRecords'?{initCloud(){}}:name==='./store'?{loadDraft:()=>privateDraft,freshDraft:()=>({actorUserId:uid(actor),restaurant:'',notes:'',photos:[],tags:[]}),saveDraft:d=>{privateDraft=d;return true;}}:null,wx:{cloud:{async callFunction({data}){const result=await handler(data);if(delayReply)await delayReply;if(slow)clock+=16000;if(loseReply&&data.action==='addWish'){loseReply=false;throw Error('lost transport reply');}return {result};}}}});return module.exports;}
 let service=client();actor='A';
 await test('client persists uncertain operation and module restart retry does not duplicate wish',async()=>{loseReply=true;await assert.rejects(service.submit('addWish',{...scope(),title:'Durable retry'}));const pending=clientIdentity.spaceIntent();assert.equal(pending.actorUserId,uid('A'));const countBefore=db.get(key('savor_spaces',space.id)).wishIds.length;service=client();await service.retry();assert.equal(db.get(key('savor_spaces',space.id)).wishIds.length,countBefore);assert.equal(clientIdentity.spaceIntent(),null);});
 await test('pending A operation never becomes B replay',async()=>{loseReply=true;await assert.rejects(service.submit('addWish',{...scope(),title:'A uncertain'}));const old=clientIdentity.spaceIntent();actor='B';generation++;await assert.rejects(service.retry(),e=>e.code==='NO_PENDING_OPERATION');assert.equal(clientIdentity.spaceIntent(),null);actor='A';generation++;assert.equal(clientIdentity.spaceIntent().args.operationId,old.args.operationId);await service.retry();});
 await test('shared response arriving after identity change is not accepted',async()=>{let release;delayReply=new Promise(r=>release=r);const pending=service.load();pending.catch(()=>{});await new Promise(setImmediate);actor='B';generation++;release();delayReply=null;await assert.rejects(pending,e=>e.code==='STALE_IDENTITY');actor='A';generation++;});
 await test('shared authorization lease is measured from request start, not late response receipt',async()=>{slow=true;await assert.rejects(service.load(),e=>e.code==='SHARED_LEASE_EXPIRED');slow=false;});
 await test('wish to private draft copies text only and never overwrites existing draft',async()=>{const w={_id:'wish',title:'New place',note:'Dinner',photos:['cloud://private'],ratings:{A:5},coordinates:[1,2]};const d=service.toDraft(w);assert.equal(d.restaurant,'New place');assert.equal(d.date,'');assert.equal(d.photos.length,0);assert(!d.ratings&&!d.coordinates);assert.equal(d.actorUserId,uid('A'));await assert.rejects(Promise.resolve().then(()=>service.toDraft(w)),e=>e.code==='DRAFT_NOT_EMPTY');});
 console.log(`${count}/${count} shared-space domain/client scenarios passed. Real CloudBase transactions and native UI NOT_EXECUTED.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
