// Pure local selectors. No uploads, shared-space reads, samples or fabricated votes.
const stats=require('./memoryStats'),dates=require('./localDate');
const escape=s=>String(s===undefined?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function build(memories,year,options={}){
 const today=dates.today(options.now),current=Number(today.slice(0,4));
 if(!Number.isInteger(year)||year<1900||year>current)throw new Error('INVALID_YEAR');
 const end=year===current?today:year+'-12-31',start=year+'-01-01';
 const all=stats.real(memories).filter(m=>m.date<=end).sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id)),rows=all.filter(m=>m.date>=start);
 const months=Array.from({length:12},(_,i)=>({month:i+1,count:year===current&&i+1>Number(today.slice(5,7))?null:rows.filter(m=>Number(m.date.slice(5,7))===i+1).length}));
 const rated=rows.filter(m=>m.ratingSource!=='legacy-average'&&(m.ratingSource==='single'||(!m.ratingSource&&!Object.keys(m.ratings||{}).length))&&Number.isInteger(m.rating)&&m.rating>0&&m.rating<=5);
 const days=[...new Set(rows.map(m=>m.date))];let streak=0,longest=0,previous=NaN;
 days.forEach(day=>{const n=dates.ordinal(day);streak=n===previous+1?streak+1:1;longest=Math.max(longest,streak);previous=n;});
 const milestones=[1,10,25,50,100,250,500,1000].filter(n=>all.length>=n&&all[n-1].date>=start).map(n=>({count:n,date:all[n-1].date}));
 const venues=new Set(rows.map(stats.placeKey).filter(Boolean));
 const report={formatVersion:1,kind:'savor-annual-report',year,asOf:end,scope:'current-owner-local-snapshot',privacy:options.details===true?'selected-details':'aggregates-only',count:rows.length,days:days.length,places:venues.size,unknownLocations:rows.filter(m=>!stats.placeKey(m)).length,longestStreak:longest,ratedCount:rated.length,averageRating:rated.length?Number((rated.reduce((n,m)=>n+m.rating,0)/rated.length).toFixed(1)):null,months,milestones};
 if(options.details===true)report.details=rows.map(m=>({date:m.date,restaurant:String(m.restaurant||''),city:m.geoConfirmed===true?String(m.city||''):'',country:m.geoConfirmed===true?String(m.country||''):''}));
 return report;
}
function html(r,locale='zh-CN'){
 const en=locale==='en',pick=(zh,enText)=>en?enText:zh,unit=(n,singular,plural)=>n===1?singular:plural;
 const max=Math.max(1,...r.months.map(m=>m.count||0));
 const bars=r.months.map(m=>'<div class="month"><span>'+escape(m.count===null?'—':m.count)+'</span><i style="height:'+Math.round((m.count||0)/max*140)+'px"></i><small>'+m.month+'</small></div>').join('');
 const metrics=[[r.count,pick('餐记录',unit(r.count,'meal record','meal records'))],[r.days,pick('记录日',unit(r.days,'recording day','recording days'))],[r.places,pick('可确认地点',unit(r.places,'confirmed place','confirmed places'))],[r.longestStreak,pick('最长连续记录天数','longest streak in days')]];
 const privacy=r.privacy==='aggregates-only'?pick('仅汇总，不含姓名、餐厅、笔记或照片','Summary only; no names, restaurants, notes or photos'):pick('已明确选择餐厅与已确认城市明细','Explicitly selected restaurant and confirmed city details');
 const rating=r.averageRating===null?pick('暂无','Not available'):r.averageRating+' / 5';
 const notes=en?'— marks future months; '+r.unknownLocations+' unknown locations are excluded from place counts. Single-rating average: '+rating+' ('+r.ratedCount+' entries). Legacy joint averages are not personal ratings.':'— 为尚未到来的月份；未知地点 '+r.unknownLocations+' 条不计入地点数。个人单评分 '+rating+'（'+r.ratedCount+' 条），不把旧双人均分当作个人评分。';
 const milestones=r.milestones.map(m=>'<div class="milestone">'+(en?'Meal milestone '+m.count:'累计第 '+m.count+' 餐')+' <span>· '+escape(m.date)+'</span></div>').join('')||'<p>'+pick('慢慢记录，不必赶进度。','Keep your memories at your own pace.')+'</p>';
 const details=r.details?'<section><h2>'+pick('主动选择分享的明细','Details explicitly selected for sharing')+'</h2><table>'+r.details.map(d=>'<tr><td>'+escape(d.date)+'</td><td>'+escape(d.restaurant)+'</td><td>'+escape([d.country,d.city].filter(Boolean).join(' · '))+'</td></tr>').join('')+'</table></section>':'';
 return '<!doctype html><html lang="'+(en?'en':'zh-CN')+'"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Savor · '+r.year+'</title><style>*{box-sizing:border-box}body{margin:0;background:#eeece9;color:#232923;font:16px system-ui,sans-serif;line-height:1.7}main{max-width:820px;margin:auto;padding:50px 26px}header{border-bottom:1px solid #c6c9c0;padding-bottom:26px}.eyebrow{letter-spacing:.2em;font-size:12px}h1{font-size:62px;font-weight:400;margin:8px 0}p{color:#5f675e}section{padding:24px 0}.metrics{display:flex;flex-wrap:wrap;gap:32px}.metrics b{font-size:36px;display:block;font-weight:400}.chart{display:flex;align-items:end;height:205px;gap:12px}.month{flex:1;text-align:center;display:flex;flex-direction:column;align-items:center}.month i{width:100%;background:#809176;min-height:2px}.month small{margin-top:8px}.milestone{border-top:1px solid #d5d6ce;padding:12px 0}table{width:100%;border-collapse:collapse}td{padding:10px 5px;border-bottom:1px solid #d5d6ce;overflow-wrap:anywhere}footer{font-size:12px;color:#687066;border-top:1px solid #c6c9c0;padding-top:22px}</style><main><header><div class="eyebrow">SAVOR / FOOD MEMORIES</div><h1>'+r.year+'</h1><div>'+pick('这一年，认真记下的每一餐','Every meal you remembered this year')+'</div><p>'+pick('截至 ','As of ')+escape(r.asOf)+' · '+privacy+'</p></header><section class="metrics">'+metrics.map(([count,label])=>'<div><b>'+count+'</b>'+label+'</div>').join('')+'</section><section><h2>'+pick('十二个月的味道','Twelve months of memories')+'</h2><div class="chart">'+bars+'</div><p>'+notes+'</p></section><section><h2>'+pick('这一年达到的里程碑','This year’s milestones')+'</h2>'+milestones+'</section>'+details+'<footer>'+pick('数据来自当前账号本机日记快照，非完整云端证明；排除示例、删除、待删除及未来记录。未读取伴侣资料。分享后无法撤回对方保存的副本。','Current-account local diary snapshot, not a complete cloud record. Examples, deleted, pending-deletion and future entries are excluded. No partner data is read. Shared copies cannot be recalled.')+'</footer></main></html>';
}
function draw(ctx,r,locale='zh-CN'){
 const en=locale==='en',pick=(zh,enText)=>en?enText:zh,unit=(n,singular,plural)=>n===1?singular:plural;
 ctx.fillStyle='#eeece9';ctx.fillRect(0,0,720,1040);ctx.fillStyle='#232923';ctx.font='20px sans-serif';ctx.fillText('SAVOR / FOOD MEMORIES',52,74);ctx.font='104px sans-serif';ctx.fillText(String(r.year),48,210);ctx.font='26px sans-serif';ctx.fillText(pick('这一年，记下的每一餐','Every meal you remembered'),52,269);ctx.fillStyle='#677260';ctx.font='18px sans-serif';ctx.fillText(pick('仅汇总 · 截至 ','Summary only · As of ')+r.asOf,52,310);
 [[pick('餐记录',unit(r.count,'Meal record','Meal records')),r.count],[pick('记录日',unit(r.days,'Recording day','Recording days')),r.days],[pick('确认地点',unit(r.places,'Confirmed place','Confirmed places')),r.places]].forEach((x,i)=>{ctx.fillStyle='#232923';ctx.font='52px sans-serif';ctx.fillText(String(x[1]),52+i*210,425);ctx.font='20px sans-serif';ctx.fillText(x[0],52+i*210,466);});
 const max=Math.max(1,...r.months.map(m=>m.count||0));r.months.forEach((m,i)=>{const x=52+i*51,h=Math.round((m.count||0)/max*170);ctx.fillStyle='#809176';ctx.fillRect(x,720-h,29,Math.max(h,2));ctx.fillStyle='#596452';ctx.font='16px sans-serif';ctx.fillText(m.count===null?'—':String(m.count),x,704-h);ctx.fillText(String(m.month),x,752);});ctx.font='21px sans-serif';ctx.fillText(en?'Longest streak: '+r.longestStreak+' '+unit(r.longestStreak,'day','days'):'最长连续记录 '+r.longestStreak+' 天',52,827);ctx.fillText(pick('里程碑：','Meal milestones: ')+(r.milestones.map(m=>m.count+pick('餐','')).join(' / ')||pick('慢慢记录，不必赶进度','At your own pace')),52,877);ctx.font='16px sans-serif';ctx.fillText(pick('当前账号本机快照 · 不含姓名、餐厅、笔记与照片','Local snapshot; no names, restaurants, notes or photos'),52,957);ctx.fillText(pick('示例及未来记录不计入；分享副本无法远程撤回。','Examples and future entries excluded. Shared copies cannot be recalled.'),52,988);
}
module.exports={build,html,draw};
